import json

# Comprehensive additional species (40 subjects)
# 22 previous + 18 new = 40 total, giving 18 + 40 = 58 subjects overall.

ADDITIONAL_SPECIES_CODE = '''import { NatureSubject } from '@/types';

export const ADDITIONAL_SUBJECTS: NatureSubject[] = [
  // ==========================================
  // MAMMALS
  // ==========================================
  {
    id: 'grizzly-bear-yellowstone',
    name: 'Interior Grizzly Bear',
    scientificName: 'Ursus arctos horribilis',
    category: 'mammal',
    tagline: 'Apex predators of Greater Yellowstone: spring cubs and autumn hyperphagia.',
    description: 'The Greater Yellowstone Ecosystem is the premier lower-48 stronghold for grizzly bears. In May and June, sows emerge with spring cubs into lush meadow valleys. In late August through October, bears enter intense hyperphagia, foraging relentlessly on roots, pine nuts, and carcasses to build winter fat stores.',
    imageUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Prominent muscular shoulder hump rising clearly above the back line',
      'Concave / dished facial profile with relatively small rounded ears',
      'Long, gently curved light-colored front digging claws (2-4 inches)'
    ],
    distinguishingTips: 'Unlike black bears, grizzlies have a pronounced shoulder hump, dished face, and long straight claws rather than short curved climbing claws.',
    states: ['WY'],
    elevationBands: ['montane', 'subalpine'],
    regions: ['wy_yellowstone_lamar', 'wy_grand_teton'],
    peakMonths: [5, 6, 9, 10],
    keyEvents: ['Spring Emergence & New Cubs (May-Jun)', 'Summer Digging & Moth Feeding (Jul-Aug)', 'Autumn Hyperphagia & Rut Carcasses (Sep-Oct)', 'Winter Denning (Nov-Apr)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Deep winter hibernation in high-elevation dens' },
      { month: 2, status: 0, keyActivity: 'Winter hibernation; cubs born in mid-winter dens' },
      { month: 3, status: 1, keyActivity: 'Large boars begin early emergence near winter-kill bison carcasses' },
      { month: 4, status: 1, keyActivity: 'Boars active on snowpack; sows with cubs still denned' },
      { month: 5, status: 2, keyActivity: 'PEAK: Sows emerge with cubs of the year; roadside grazing on succulent dandelion greens' },
      { month: 6, status: 2, keyActivity: 'PEAK: Active meadow foraging, elk calf hunting, breeding pair encounters' },
      { month: 7, status: 1, keyActivity: 'Bears move to high talus for army cutworm moths and pocket gophers' },
      { month: 8, status: 1, keyActivity: 'Whitebark pine nut foraging at timberline; bears begin hyperphagia' },
      { month: 9, status: 2, keyActivity: 'PEAK: Intense pre-denning hyperphagia; heavy feeding along river bottoms and meadows' },
      { month: 10, status: 2, keyActivity: 'PEAK: Thick winter coats; scavenging elk rut casualties against frosted sagebrush' },
      { month: 11, status: 1, keyActivity: 'Bears ascend toward den sites in deep snow' },
      { month: 12, status: 0, keyActivity: 'Most bears settled into winter dens' },
    ],
    hotspots: [
      {
        name: 'Pilgrim Creek & Willow Flats (Grand Teton)',
        region: 'wy_grand_teton',
        state: 'WY',
        elevation: '6,800 ft',
        publicLandType: 'National Park',
        accessNotes: 'Historic territory of famous matriarch Grizzly 399 and her descendants. Willow Flats overlook offers elevated shooting.',
        bestTime: 'Sunrise and golden hour dusk',
        lat: 43.8656,
        lng: -110.5847,
      },
      {
        name: 'Hayden Valley & Pelican Creek (Yellowstone)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '7,700 ft',
        publicLandType: 'National Park',
        accessNotes: 'Panoramic valley views along the Yellowstone River corridor with roadside pullouts.',
        bestTime: 'Early morning mist lift (6:00 AM - 9:00 AM)',
        lat: 44.6367,
        lng: -110.4633,
      },
      {
        name: 'Lamar Valley & Soda Butte Creek (Yellowstone)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '6,600 ft',
        publicLandType: 'National Park',
        accessNotes: 'The American Serengeti. Expansive sage flats where bears patrol bison herds and bison carcasses.',
        bestTime: 'First two hours of morning light',
        lat: 44.8967,
        lng: -110.2393,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['500mm or 600mm f/4 prime', '100-400mm or 180-600mm telephoto zoom', '1.4x teleconverter'],
      bestLighting: 'Front-lit early morning sun; backlit sunset highlighting golden guard hairs.',
      fieldBehaviorNotes: 'Use car window mounts or heavy carbon tripods from designated pullouts. Sows with cubs move unpredictably; never block their path.',
      ethicalGuidelines: 'STRICT NPS REGULATION: Maintain minimum 100 yards (300 ft) distance at all times. Carry bear spray on your hip, not inside your bag.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'american-black-bear',
    name: 'American Black Bear',
    scientificName: 'Ursus americanus',
    category: 'mammal',
    tagline: 'Climbing spring cubs and autumn acorn gorges in ancient hardwood & aspen forests.',
    description: 'Black bears thrive across mountainous forests from Colorado’s Gambel oak corridors to Tennessee’s Great Smoky Mountains. Watch for spring cubs learning to scramble up ponderosa and tuliptrees, and massive autumn bruins gorging on acorns and chokecherries.',
    imageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Straight Roman nose profile from forehead to nose tip without a dip',
      'No pronounced shoulder hump; rump is typically higher than the shoulders',
      'Large, more pointed and prominent ears than a grizzly'
    ],
    distinguishingTips: 'Color can range from pitch black to cinnamon brown and blonde; check the straight facial profile and lack of a shoulder hump to avoid misidentifying brown-phase black bears as grizzlies.',
    states: ['CO', 'TN', 'NC', 'WA'],
    elevationBands: ['foothills', 'montane'],
    regions: ['app_great_smokies', 'co_san_juan', 'co_rmnp_frontrange', 'pnw_cascades_rainier'],
    peakMonths: [5, 6, 9, 10],
    keyEvents: ['Spring Emergence & Tree-climbing Cubs (May-Jun)', 'Summer Berries (Jul-Aug)', 'Autumn Acorn & Oak Mast Feeding (Sep-Oct)', 'Winter Denning (Dec-Mar)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Winter denning in hollow logs, rock dens, or excavated burrows' },
      { month: 2, status: 0, keyActivity: 'Denning; newborn cubs nursing inside secure dens' },
      { month: 3, status: 1, keyActivity: 'Early thaw emergence in southern ranges (Smokies)' },
      { month: 4, status: 1, keyActivity: 'Bears feed on early spring grasses and skunk cabbage' },
      { month: 5, status: 2, keyActivity: 'PEAK: Sows with tiny spring cubs emerge; cubs climb trees when alarmed' },
      { month: 6, status: 2, keyActivity: 'PEAK: Active foraging in mountain pastures, meadows, and forest edges' },
      { month: 7, status: 1, keyActivity: 'Serviceberry, raspberry, and chokecherry feeding' },
      { month: 8, status: 1, keyActivity: 'High country blueberry feeding and blackberry thickets' },
      { month: 9, status: 2, keyActivity: 'PEAK: Hyperphagia in Gambel oak brush and hardwood acorn groves' },
      { month: 10, status: 2, keyActivity: 'PEAK: Maximum body weight, thick glossy winter coats against autumn foliage' },
      { month: 11, status: 1, keyActivity: 'Bears slow down and retreat to winter den locations' },
      { month: 12, status: 0, keyActivity: 'Winter hibernation' },
    ],
    hotspots: [
      {
        name: 'Cades Cove Loop Road (Great Smoky Mountains)',
        region: 'app_great_smokies',
        state: 'TN',
        elevation: '1,800 ft',
        publicLandType: 'National Park',
        accessNotes: '11-mile one-way loop with open pastures, walnut trees, and old home sites. Prime black bear density.',
        bestTime: 'Early morning or late afternoon before gates close',
        lat: 35.6025,
        lng: -83.8183,
      },
      {
        name: 'Ouray & Red Mountain Pass Oak Flats (San Juans)',
        region: 'co_san_juan',
        state: 'CO',
        elevation: '7,800 - 9,500 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Steep hillsides covered in chokecherry and Gambel oak where cinnamon and black phase bears feed.',
        bestTime: 'Morning and late afternoon golden hour',
        lat: 37.9867,
        lng: -107.6719,
      },
      {
        name: 'Wild Basin & Horseshoe Park (Rocky Mountain NP)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '8,500 ft',
        publicLandType: 'National Park',
        accessNotes: 'Aspen margins and riparian wetlands near beaver ponds.',
        bestTime: 'Early morning twilight',
        lat: 40.2089,
        lng: -105.5658,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['100-400mm f/4.5-5.6', '400mm f/2.8 or f/4 telephoto', '70-200mm for contextual environmental portraits'],
      bestLighting: 'Filtered canopy light on overcast days; deep forest backlight highlighting outline fur.',
      fieldBehaviorNotes: 'Black bear cubs will scamper up trees at the first sign of danger while the mother stands guard at the base. Keep silent and do not crowd.',
      ethicalGuidelines: 'National Park rules require 50 yards minimum distance. Never feed or position yourself between a sow and her cubs.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'rocky-mountain-goat',
    name: 'Rocky Mountain Goat',
    scientificName: 'Oreamnos americanus',
    category: 'mammal',
    tagline: 'Acrobats of the vertical abyss: shaggy white coats and needle-sharp black horns on alpine crags.',
    description: 'Masters of vertical cliff terrain, mountain goats thrive on high precipitous alpine ledges where predators cannot follow. In summer, billies and nannies graze alpine tundra basins in shaggy molting fleece, while playful kids scramble fearlessly across sheer 14,000-ft cliff faces.',
    imageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Dense, all-white woolly double coat with a distinctive beard and shoulder crest',
      'Slender, glossy jet-black horns that curve gently backward without spiraling',
      'Deep chest, stout muscular legs, and black rubbery hooves with suction pads'
    ],
    distinguishingTips: 'Unlike Bighorn Sheep which have brown spiraling curled horns and tan coats, Mountain Goats are pure white with slender black dagger-like horns.',
    states: ['CO', 'WA'],
    elevationBands: ['alpine'],
    regions: ['co_rmnp_frontrange', 'co_central_rockies', 'pnw_cascades_rainier'],
    peakMonths: [6, 7, 8],
    keyEvents: ['Early Summer Kids on Crags (Jun-Jul)', 'Fleece Molting on Rocks (Jul)', 'Pre-winter Coat Growth (Sep-Oct)'],
    phenology: [
      { month: 1, status: 1, keyActivity: 'Surviving on wind-scoured southern cliff faces' },
      { month: 2, status: 1, keyActivity: 'Sheltered in high cliff alcoves' },
      { month: 3, status: 1, keyActivity: 'Feeding on lichens and dried bunchgrasses on cliffs' },
      { month: 4, status: 1, keyActivity: 'Nannies seek inaccessible cliff ledges for kidding' },
      { month: 5, status: 1, keyActivity: 'Kids born on vertical rock ledges' },
      { month: 6, status: 2, keyActivity: 'PEAK: Playful kids scampering after nannies on alpine tundra passes' },
      { month: 7, status: 2, keyActivity: 'PEAK: High social interaction; licking mineral salts near parking summits' },
      { month: 8, status: 2, keyActivity: 'PEAK: Prime photography along alpine summit roads before early blizzards' },
      { month: 9, status: 1, keyActivity: 'Growing dense winter underwool; coats turn pristine white' },
      { month: 10, status: 1, keyActivity: 'Rutting displays begin on high ridges' },
      { month: 11, status: 1, keyActivity: 'Intense November rut amid snow and ice' },
      { month: 12, status: 1, keyActivity: 'Winter survival on sheer granite precipices' },
    ],
    hotspots: [
      {
        name: 'Mount Blue Sky Summit & Summit Lake (Front Range)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '12,830 - 14,130 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Paved highway directly to 14,000-ft summit. Goats frequently lick salt near trailheads and graze tundra.',
        bestTime: 'Early morning (7:00 AM - 10:00 AM) before afternoon storms',
        lat: 39.5883,
        lng: -105.6438,
      },
      {
        name: 'Collegiate Peaks & Cottonwood Pass (Sawatch Range)',
        region: 'co_central_rockies',
        state: 'CO',
        elevation: '12,126 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Paved continental divide pass with expansive alpine tundra ridge walks.',
        bestTime: 'Morning sun illuminating granite talus',
        lat: 38.8281,
        lng: -106.4094,
      },
      {
        name: 'Mount Rainier Panhandle Gap (Cascades)',
        region: 'pnw_cascades_rainier',
        state: 'WA',
        elevation: '6,800 ft',
        publicLandType: 'National Park',
        accessNotes: 'Wonderland Trail alpine traverse past permanent snowfields and glacial moraines.',
        bestTime: 'Morning alpine light',
        lat: 46.8500,
        lng: -121.6500,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['70-200mm f/2.8', '100-400mm telephoto zoom'],
      bestLighting: 'Morning side-light highlights the textured layers of white wool without blowing out highlights.',
      fieldBehaviorNotes: 'Goats crave minerals and will approach parked vehicles or hikers to lick salt. Give them at least 50 feet and never corner them on narrow ledge trails.',
      ethicalGuidelines: 'Do not allow goats to lick perspiration off your clothing or pack; keep a safe perimeter.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'canada-lynx',
    name: 'Canada Lynx',
    scientificName: 'Lynx canadensis',
    category: 'mammal',
    tagline: 'Snowshoe paws and tufted ears: ghost hunter of subalpine spruce-fir snowpacks.',
    description: 'Specially adapted for deep powder snow, the Canada Lynx is characterized by enormous furry paws that function like snowshoes, dramatic black ear tufts over an inch long, and an abbreviated black-tipped tail. Colorado is home to a successfully reintroduced subalpine population in the San Juan Mountains.',
    imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Very long black ear tufts (over 1 inch) and flared facial ruffs',
      'Enormous, densely furred round paws acting as natural snowshoes',
      'Completely black-tipped stubby tail (solid black all around the tip)'
    ],
    distinguishingTips: 'Unlike the Bobcat which has smaller paws, shorter ear tufts, and a tail with white on the underside of the tip, the Lynx has giant furry paws and a completely black tail tip.',
    states: ['CO', 'WA'],
    elevationBands: ['subalpine'],
    regions: ['co_san_juan', 'co_central_rockies', 'pnw_cascades_rainier'],
    peakMonths: [1, 2, 12],
    keyEvents: ['Winter Snow Tracking & Hare Pursuits (Jan-Feb)', 'Mating Season Calls (Mar)', 'Kitten Denning in Deadfall (May-Jun)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High snowpack forces cats to hunt snowshoe hares along forest edges in daylight' },
      { month: 2, status: 2, keyActivity: 'PEAK: Courtship pairs traveling together; clear tracks through deep powder' },
      { month: 3, status: 1, keyActivity: 'Mating season in deep subalpine spruce-fir' },
      { month: 4, status: 1, keyActivity: 'Females seek large root-tangle blowdowns for maternity dens' },
      { month: 5, status: 1, keyActivity: 'Kittens born in remote deadfall tangles' },
      { month: 6, status: 0, keyActivity: 'Mother strictly hunting within small radius of den' },
      { month: 7, status: 0, keyActivity: 'Kittens begin traveling with mother' },
      { month: 8, status: 0, keyActivity: 'Secretive summer foraging in dense spruce forests' },
      { month: 9, status: 1, keyActivity: 'Juveniles practicing hare hunts' },
      { month: 10, status: 1, keyActivity: 'Winter undercoat and thick footpad fur develops' },
      { month: 11, status: 1, keyActivity: 'First persistent snowpack; daylight hunting resumes' },
      { month: 12, status: 2, keyActivity: 'PEAK: Pristine winter snow conditions for tracking and photographing' },
    ],
    hotspots: [
      {
        name: 'Molise & Silverton High Passes (San Juan Mountains)',
        region: 'co_san_juan',
        state: 'CO',
        elevation: '10,500 - 11,200 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Core reintroduction area in southwest Colorado. High density of snowshoe hares.',
        bestTime: 'Overcast winter mornings after fresh snow',
        lat: 37.8100,
        lng: -107.6600,
      },
      {
        name: 'Vail Pass & Shrine Pass High Ridges',
        region: 'co_central_rockies',
        state: 'CO',
        elevation: '10,600 - 11,000 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Subalpine spruce-fir forests with wildlife overpass structures along I-70.',
        bestTime: 'Dawn twilight',
        lat: 39.5292,
        lng: -106.2186,
      },
      {
        name: 'North Cascades Pasayten Wilderness Fringe',
        region: 'pnw_cascades_rainier',
        state: 'WA',
        elevation: '5,000 - 6,500 ft',
        publicLandType: 'Wilderness Area',
        accessNotes: 'Dense lodgepole and spruce burn recovery zones with thriving hare populations.',
        bestTime: 'Early morning snowshoe trek',
        lat: 48.7500,
        lng: -120.5000,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['400mm f/2.8 or 500mm f/4', 'Snowshoes and cold-weather battery warmers'],
      bestLighting: 'Soft overcast winter light prevents harsh snow contrast and reveals subtle silvery-buff fur tones.',
      fieldBehaviorNotes: 'Lynx have immense patience and will sit calmly watching humans from 40 yards away. Move slowly on snowshoes without making sudden loud clicks.',
      ethicalGuidelines: 'Federal Threatened Species. Never pursue or run after a lynx; let the cat dictate the encounter distance.',
      difficultyRating: 'Rugged Alpine Backcountry',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'river-otter',
    name: 'North American River Otter',
    scientificName: 'Lontra canadensis',
    category: 'mammal',
    tagline: 'Playful stream acrobats: belly sliding on icy snowbanks and hunting cutthroat trout.',
    description: 'Charming, sleek, and boundlessly energetic, North American river otters have made an inspiring comeback in clean mountain waterways. In winter, they are famous for tobogganing down snowbanks on their bellies into icy plunge holes, surfacing with wriggling trout on frozen river shelves.',
    imageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Streamlined cylindrical body with dense waterproof dark brown pelt',
      'Broad flattened head with long sensitive sensory vibrissae (whiskers)',
      'Thick muscular tail that tapers smoothly toward the tip, and webbed feet'
    ],
    distinguishingTips: 'Much larger than mink; distinctly muscular tapering tail (mink tail is uniformly bushy); swims with head, back, and tail visible in a characteristic undulating wave.',
    states: ['CO', 'WY', 'WA'],
    elevationBands: ['foothills', 'montane'],
    regions: ['co_rmnp_frontrange', 'wy_yellowstone_lamar', 'pnw_olympic_rainforest'],
    peakMonths: [1, 2, 12],
    keyEvents: ['Winter Snow Sliding & Ice Diving (Jan-Feb)', 'Spring Pups in Dens (Apr-May)', 'Family Rafts Fishing (Jul-Aug)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High visibility on frozen rivers; sliding down snow chutes into open water holes' },
      { month: 2, status: 2, keyActivity: 'PEAK: Pairs and family groups active in daylight on river ice shelves' },
      { month: 3, status: 1, keyActivity: 'Courtship along ice-free river stretches' },
      { month: 4, status: 1, keyActivity: 'Females whelp pups in abandoned beaver lodges or riverbank burrows' },
      { month: 5, status: 1, keyActivity: 'Pups remain in den; mother hunts nearby riffles' },
      { month: 6, status: 1, keyActivity: 'Mother introduces pups to swimming in calm river backwaters' },
      { month: 7, status: 1, keyActivity: 'Family groups foraging together on crayfish and suckers' },
      { month: 8, status: 1, keyActivity: 'Active morning and evening feeding in mountain lakes' },
      { month: 9, status: 1, keyActivity: 'Exploring tributary streams as trout spawn' },
      { month: 10, status: 1, keyActivity: 'Dense winter underfur develops' },
      { month: 11, status: 1, keyActivity: 'Patrolling expanding ice edges' },
      { month: 12, status: 2, keyActivity: 'PEAK: Fresh snow provides belly-sliding tracks along river bends' },
    ],
    hotspots: [
      {
        name: 'Colorado River Headwaters (Kawuneeche Valley, RMNP)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '8,700 ft',
        publicLandType: 'National Park',
        accessNotes: 'Meandering river valley with beaver ponds and open winter riffles along Trail Ridge Road.',
        bestTime: 'Morning sun warming the riverbanks',
        lat: 40.3800,
        lng: -105.8500,
      },
      {
        name: 'Yellowstone River / Trout Creek (Hayden Valley)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '7,700 ft',
        publicLandType: 'National Park',
        accessNotes: 'Geothermal runoff keeps river sections ice-free all winter.',
        bestTime: 'Midday sunny hours when otters sun on ice shelves',
        lat: 44.6400,
        lng: -110.4600,
      },
      {
        name: 'Hoh River Estuary & Olympic Coastal Streams',
        region: 'pnw_olympic_rainforest',
        state: 'WA',
        elevation: '200 ft',
        publicLandType: 'National Park',
        accessNotes: 'Lush rainforest riverbanks lined with fallen mossy cedar logs.',
        bestTime: 'Morning low tide',
        lat: 47.7500,
        lng: -124.3800,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['100-400mm or 400mm f/4.5', 'High frame rate (20+ fps) for sliding and diving action'],
      bestLighting: 'Bright morning side-light to highlight glistening water droplets on waterproof fur.',
      fieldBehaviorNotes: 'Otters are curious. If you sit quietly on a riverbank without moving, they will often pop up in the water, tread water to peer at you, and snort before diving.',
      ethicalGuidelines: 'Do not approach open ice holes where otters feed; thin ice is hazardous to both you and the animals.',
      difficultyRating: 'Moderate Hike',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'american-badger',
    name: 'American Badger',
    scientificName: 'Taxidea taxus',
    category: 'mammal',
    tagline: 'Fierce prairie excavator: bold black-and-white facial stripes and subterranean burrowing.',
    description: 'Built like a miniature tank with short muscular legs and enormous curved digging claws, the American Badger is the subterranean master of North American grasslands and sagebrush steppe. Often seen hunting cooperatively near coyotes or excavating prairie dog burrows in clouds of flying dirt.',
    imageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Bold black-and-white striped facial mask with white stripe extending down snout',
      'Stocky, low-slung flattened body covered in grizzled silvery-gray fur',
      'Massive, formidable curved front claws (up to 2 inches long) designed for rapid digging'
    ],
    distinguishingTips: 'Distinctive flattened body profile, black facial badges behind eyes, and powerful excavation claws distinguish it from wolverines or skunks.',
    states: ['CO', 'WY'],
    elevationBands: ['plains', 'foothills', 'montane'],
    regions: ['co_eastern_plains', 'co_north_park', 'wy_yellowstone_lamar'],
    peakMonths: [5, 6, 7],
    keyEvents: ['Spring Pups at Burrow Entrance (May-Jun)', 'Hunting Cooperation with Coyotes (Jul-Aug)', 'Pre-winter Fat Storage (Sep-Oct)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Winter torpor inside deep burrows' },
      { month: 2, status: 0, keyActivity: 'Brief emergence during warm sunny winter afternoons' },
      { month: 3, status: 1, keyActivity: 'Active excavation of hunting burrows resumes' },
      { month: 4, status: 1, keyActivity: 'Females give birth in deep grass-lined chambers' },
      { month: 5, status: 2, keyActivity: 'PEAK: Mothers and playful young pups sunning outside burrow entrance' },
      { month: 6, status: 2, keyActivity: 'PEAK: High daylight foraging activity in prairie dog colonies' },
      { month: 7, status: 2, keyActivity: 'PEAK: Active hunting along sagebrush flats; fascinating coyote associations' },
      { month: 8, status: 1, keyActivity: 'Juveniles disperse into independent territories' },
      { month: 9, status: 1, keyActivity: 'Heavy feeding to accumulate thick winter adipose fat' },
      { month: 10, status: 1, keyActivity: 'Dense winter fur develops; digging winter dens' },
      { month: 11, status: 0, keyActivity: 'Activity declines as cold weather sets in' },
      { month: 12, status: 0, keyActivity: 'Winter torpor' },
    ],
    hotspots: [
      {
        name: 'Pawnee National Grassland (Eastern Plains)',
        region: 'co_eastern_plains',
        state: 'CO',
        elevation: '5,100 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Expansive prairie dog colonies along dirt county roads.',
        bestTime: 'Morning and evening golden hours',
        lat: 40.8000,
        lng: -104.2500,
      },
      {
        name: 'Lamar Valley Sage Steppe (Yellowstone)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '6,600 ft',
        publicLandType: 'National Park',
        accessNotes: 'Open sage flats where badgers and coyotes frequently hunt Uinta ground squirrels together.',
        bestTime: 'Morning (7:00 AM - 10:00 AM)',
        lat: 44.9000,
        lng: -110.2200,
      },
      {
        name: 'Arapaho National Wildlife Refuge (Walden)',
        region: 'co_north_park',
        state: 'CO',
        elevation: '8,150 ft',
        publicLandType: 'Wildlife Refuge',
        accessNotes: 'Intermountain sagebrush basin with high Richardson ground squirrel populations.',
        bestTime: 'Late afternoon before dusk',
        lat: 40.6500,
        lng: -106.2800,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['500mm f/4 or 600mm f/4', 'Ground pod for low eye-level perspective'],
      bestLighting: 'Warm low sun angles casting warm light into the badger’s dark facial mask.',
      fieldBehaviorNotes: 'Badgers will frequently stand up on their hind legs to peer over grass, or hiss and snort if approached too closely. Maintain safe distance with a long lens.',
      ethicalGuidelines: 'Do not crowd active maternal dens. If the female retreats underground and will not emerge, move away immediately.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'american-pine-marten',
    name: 'American Pine Marten',
    scientificName: 'Martes americana',
    category: 'mammal',
    tagline: 'Tree canopy acrobat: bright inquisitive eyes, silky golden bib, and agile pine jumps.',
    description: 'Weasel-family aristocrats of the ancient subalpine spruce-fir forest, pine martens are lightning-fast canopy climbers with inquisitive fox-like faces and beautiful orange-gold throat patches. In winter, they bound over deep snowbanks and leap between tree branches hunting red squirrels and voles.',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Warm brown to chocolate silky fur with a brilliant cream to orange throat and chest bib',
      'Sharp, pointed triangular face with large rounded ears and dark alert eyes',
      'Long bushy tail (one-third of total length) and semi-retractable climbing claws'
    ],
    distinguishingTips: 'Smaller and much more arboreal than a fisher or otter; the prominent bright orange or peach chest bib and large ears are diagnostic.',
    states: ['CO', 'WY', 'WA'],
    elevationBands: ['montane', 'subalpine'],
    regions: ['co_rmnp_frontrange', 'wy_grand_teton', 'pnw_cascades_rainier'],
    peakMonths: [1, 2, 12],
    keyEvents: ['Winter Snow Tracking around Lodges (Dec-Feb)', 'Mating Season (Jul-Aug)', 'Kits in Hollow Snags (Apr-May)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High daylight visibility; patrolling ski trails and subalpine cabins for rodent caches' },
      { month: 2, status: 2, keyActivity: 'PEAK: Bounding through fresh snow; hunting under fallen logs' },
      { month: 3, status: 1, keyActivity: 'Sub-nivean (under-snow) tunnel hunting' },
      { month: 4, status: 1, keyActivity: 'Females give birth in high hollow tree cavities' },
      { month: 5, status: 1, keyActivity: 'Mother delivers voles to tree cavity nests' },
      { month: 6, status: 1, keyActivity: 'Young kits learn to climb rough spruce bark' },
      { month: 7, status: 1, keyActivity: 'Summer foraging on berries and insects' },
      { month: 8, status: 1, keyActivity: 'Summer mating season; vocalizations in canopy' },
      { month: 9, status: 1, keyActivity: 'Dispersal through mature contiguous forest' },
      { month: 10, status: 1, keyActivity: 'Dense winter fur fills in' },
      { month: 11, status: 1, keyActivity: 'First persistent snows; hunting around backcountry shelters' },
      { month: 12, status: 2, keyActivity: 'PEAK: Bold visits around subalpine warming huts and snowshoe trails' },
    ],
    hotspots: [
      {
        name: 'Bear Lake & Glacier Gorge Trailheads (RMNP)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '9,475 ft',
        publicLandType: 'National Park',
        accessNotes: 'Mature Engelmann spruce and subalpine fir forests around the winter trailheads.',
        bestTime: 'Morning hours following fresh snowfall',
        lat: 40.3120,
        lng: -105.6460,
      },
      {
        name: 'String Lake & Jenny Lake Forest Trails (Grand Teton)',
        region: 'wy_grand_teton',
        state: 'WY',
        elevation: '6,870 ft',
        publicLandType: 'National Park',
        accessNotes: 'Lakeside old-growth forest with abundant fallen timber and red squirrel middens.',
        bestTime: 'Early morning quiet hours',
        lat: 43.7900,
        lng: -110.7300,
      },
      {
        name: 'Longmire & Paradise Winter Trails (Mount Rainier)',
        region: 'pnw_cascades_rainier',
        state: 'WA',
        elevation: '2,700 - 5,400 ft',
        publicLandType: 'National Park',
        accessNotes: 'Ancient Douglas fir and western hemlock stands with deep winter snow pack.',
        bestTime: 'Mid-morning soft overcast light',
        lat: 46.7500,
        lng: -121.8100,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['70-200mm f/2.8 or 300mm f/4', 'Fast shutter speed (1/1600s) to freeze rapid tree leaps'],
      bestLighting: 'Soft filtered forest light or snow-reflected upward fill light illuminating the rich orange chest bib.',
      fieldBehaviorNotes: 'Martens are intensely curious. If one spots you, it will often poke its head out from behind a tree trunk, duck, and reappear five feet higher to investigate.',
      ethicalGuidelines: 'Never bait martens with food; keep human food and gear tightly sealed.',
      difficultyRating: 'Moderate Hike',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },
  {
    id: 'north-american-porcupine',
    name: 'North American Porcupine',
    scientificName: 'Erethizon dorsatum',
    category: 'mammal',
    tagline: 'Quilled tree-dweller: perched in snowy ponderosa crowns and willow groves.',
    description: 'Armed with over 30,000 barbed defensive quills, North American porcupines are gentle, slow-moving herbivores of the western forests. In winter, they spend days high in the branches of ponderosa pines and willows feeding on inner bark (cambium), appearing like giant dark silhouettes frosted with rime ice.',
    imageUrl: 'https://images.unsplash.com/photo-1500463959177-e0869687df26?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Dense body covered in sharp, yellowish-white quills with black tips',
      'Long dark guard hairs that conceal the quills until alarmed',
      'Blunt, heavy dark muzzle with small beady eyes and large orange incisors'
    ],
    distinguishingTips: 'Completely unique silhouette in North America; unmistakable ball-like shape perched high in bare winter tree branches.',
    states: ['CO', 'WY'],
    elevationBands: ['foothills', 'montane'],
    regions: ['co_rmnp_frontrange', 'co_san_juan', 'wy_yellowstone_lamar'],
    peakMonths: [1, 2, 12],
    keyEvents: ['Winter Cambium Feeding in Bare Trees (Dec-Feb)', 'Spring Porcupettes Born (May)', 'Autumn Breeding Season (Oct)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High visibility high in leafless cottonwoods and open ponderosa crowns' },
      { month: 2, status: 2, keyActivity: 'PEAK: Sunning in tree crotches on cold clear winter afternoons' },
      { month: 3, status: 1, keyActivity: 'Feeding on pine needles and tender buds' },
      { month: 4, status: 1, keyActivity: 'Descending to feed on early ground vegetation' },
      { month: 5, status: 1, keyActivity: 'Single soft-quilled "porcupette" born in rock den or hollow log' },
      { month: 6, status: 1, keyActivity: 'Mother and young foraging on succulent willow shoots' },
      { month: 7, status: 1, keyActivity: 'Feeding on lush forbs and aquatic plants' },
      { month: 8, status: 1, keyActivity: 'Feeding on berries and seeds' },
      { month: 9, status: 1, keyActivity: 'Vocal mating calls in autumn forest' },
      { month: 10, status: 1, keyActivity: 'Courtship rituals and mating season' },
      { month: 11, status: 1, keyActivity: 'Ascending back into canopy as snow deepens' },
      { month: 12, status: 2, keyActivity: 'PEAK: Heavy bark feeding creates visible debarked white wood patches in trees' },
    ],
    hotspots: [
      {
        name: 'Rocky Mountain Arsenal NWR Cottonwood Groves (Denver)',
        region: 'co_eastern_plains',
        state: 'CO',
        elevation: '5,280 ft',
        publicLandType: 'Wildlife Refuge',
        accessNotes: 'Mature cottonwood galleries along lakes and stream corridors.',
        bestTime: 'Morning and late afternoon looking up into bare branches',
        lat: 39.8160,
        lng: -104.8450,
      },
      {
        name: 'Mora Campground & Upper Beaver Meadows (RMNP)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '8,200 ft',
        publicLandType: 'National Park',
        accessNotes: 'Open ponderosa pine forest and willow riparian bottom.',
        bestTime: 'Midday sunny hours when animals sun themselves in tree crotches',
        lat: 40.3700,
        lng: -105.5800,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['100-400mm or 70-200mm telephoto zoom'],
      bestLighting: 'Backlight illuminates the long halo of frosty guard hairs surrounding the animal.',
      fieldBehaviorNotes: 'Porcupines cannot throw their quills! However, if alarmed, they will turn their back, chatter their teeth, and swing their heavy quilled tail.',
      ethicalGuidelines: 'Keep dogs on leash; porcupine encounters are painful and require veterinary intervention.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'PawPrint',
    colorAccent: 'amber',
  },

  // ==========================================
  // BIRDS
  // ==========================================
  {
    id: 'great-gray-owl',
    name: 'Great Gray Owl',
    scientificName: 'Strix nebulosa',
    category: 'bird',
    tagline: 'The Phantom of the North: colossal concentric facial discs and silent snow plunging.',
    description: 'North America’s largest owl by length, the Great Gray Owl is the phantom master of subalpine mountain meadows. With enormous concentric facial discs that act like satellite dishes, they can pinpoint the sound of a vole tunneling under three feet of crusted snow, hovering and plunging face-first through the snowpack.',
    imageUrl: 'https://images.unsplash.com/photo-1516331138075-f3adc1e149cd?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Massive circular concentric facial disc with fine dark rings and white "bow-tie" neck marks',
      'Piercing yellow eyes that appear relatively small within the colossal facial disc',
      'Fluffy ash-gray plumage with heavily barred underparts and no ear tufts'
    ],
    distinguishingTips: 'Much larger facial disc than a Barred Owl; yellow eyes (Barred Owl has dark brown eyes); lacks the feather horns of a Great Horned Owl.',
    states: ['WY', 'WA'],
    elevationBands: ['montane', 'subalpine'],
    regions: ['wy_grand_teton', 'wy_yellowstone_lamar', 'pnw_cascades_rainier'],
    peakMonths: [1, 2, 5, 6],
    keyEvents: ['Winter Snow Plunging for Voles (Jan-Feb)', 'Dawn and Dusk Meadow Perching (May-Jun)', 'Fledglings on Fallen Logs (Jul)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: Daylight hunting over deep snowfields; spectacular plunging dives into powder' },
      { month: 2, status: 2, keyActivity: 'PEAK: Territorial hooting at twilight; hunting open meadow edges' },
      { month: 3, status: 1, keyActivity: 'Pairs claim broken-top tree snags or abandoned raven nests' },
      { month: 4, status: 1, keyActivity: 'Females incubating eggs atop broken snags' },
      { month: 5, status: 2, keyActivity: 'PEAK: Downy chicks in nest; males hunt relentlessly in daylight to feed family' },
      { month: 6, status: 2, keyActivity: 'PEAK: Fledglings climb leaning tree trunks using beak and talons' },
      { month: 7, status: 1, keyActivity: 'Juveniles practicing flights between forest perches' },
      { month: 8, status: 1, keyActivity: 'Nocturnal and crepuscular meadow hunting' },
      { month: 9, status: 1, keyActivity: 'Foraging along lodgepole pine edges' },
      { month: 10, status: 1, keyActivity: 'Dispersing as high country freezes' },
      { month: 11, status: 1, keyActivity: 'Daytime hunting resumes as snowpack accumulates' },
      { month: 12, status: 2, keyActivity: 'PEAK: Striking winter portraits against frosted evergreen boughs' },
    ],
    hotspots: [
      {
        name: 'Moose-Wilson Road & Signal Mountain Meadows (Grand Teton)',
        region: 'wy_grand_teton',
        state: 'WY',
        elevation: '6,600 ft',
        publicLandType: 'National Park',
        accessNotes: 'Lush meadow corridors bordering mature spruce-fir and aspen groves.',
        bestTime: 'Overcast afternoons and the last two hours of daylight',
        lat: 43.6800,
        lng: -110.7400,
      },
      {
        name: 'Tower Fall & Blacktail Plateau (Yellowstone)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '6,800 ft',
        publicLandType: 'National Park',
        accessNotes: 'Douglas fir and lodgepole forest glades overlooking sage meadows.',
        bestTime: 'Dawn and dusk',
        lat: 44.9100,
        lng: -110.4200,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['400mm f/2.8 or 500mm f/4', 'Sturdy monopod for quick meadow adjustments'],
      bestLighting: 'Overcast diffuse light or golden hour sidelight illuminating the concentric facial disc rings.',
      fieldBehaviorNotes: 'Great Gray Owls are remarkably tolerant of quiet observers. If one lands on a nearby branch, stay still, keep low, and never play recorded calls.',
      ethicalGuidelines: 'NEVER use live mice to bait owls. Baiting habituates raptors to roadsides and leads to vehicle strikes.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'Feather',
    colorAccent: 'sky',
  },
  {
    id: 'golden-eagle',
    name: 'Golden Eagle',
    scientificName: 'Aquila chrysaetos',
    category: 'bird',
    tagline: 'Monarch of western canyon skies: golden nape hackles and 7-foot soaring wingspan.',
    description: 'The Golden Eagle is North America’s premier aerial apex predator. Soaring effortlessly on thermals with a seven-foot wingspan, these massive raptors patrol rugged canyon cliffs, open sagebrush valleys, and alpine ridges, capable of diving at speeds over 150 mph to strike jackrabbits, marmots, and prairie dogs.',
    imageUrl: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Luminous golden-buff hackle feathers on the nape of the neck',
      'Rich dark chocolate-brown body with long broad wings slightly upturned in a slight "V" in soaring flight',
      'Legs fully feathered all the way down to the yellow talons (unlike Bald Eagles)'
    ],
    distinguishingTips: 'Distinguished from immature Bald Eagles by fully feathered legs all the way to the toes, golden nape, and a smaller, less massive bill.',
    states: ['CO', 'WY', 'UT'],
    elevationBands: ['foothills', 'montane', 'alpine'],
    regions: ['co_gunnison_crested_butte', 'co_rmnp_frontrange', 'sw_moab_arches'],
    peakMonths: [1, 2, 6, 7],
    keyEvents: ['Winter Scavenging on Valley Carcasses (Jan-Feb)', 'Cliff Eyrie Nesting (Apr-May)', 'Aerial Thermal Soaring (Jun-Aug)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High valley visibility; feeding on winter-kill and jackrabbits' },
      { month: 2, status: 2, keyActivity: 'PEAK: Spectacular aerial courtship displays; roller-coaster dives and talon grappling' },
      { month: 3, status: 1, keyActivity: 'Repairing massive stick nests on sheer canyon cliff faces' },
      { month: 4, status: 1, keyActivity: 'Incubation on cliff ledges' },
      { month: 5, status: 1, keyActivity: 'Chicks hatch; adults hunt marmots in open basins' },
      { month: 6, status: 2, keyActivity: 'PEAK: High hunting activity delivering prey to canyon eyries' },
      { month: 7, status: 2, keyActivity: 'PEAK: Fledglings soaring along canyon rim thermals' },
      { month: 8, status: 1, keyActivity: 'Riding alpine thermals hunting pikas and marmots above treeline' },
      { month: 9, status: 1, keyActivity: 'Autumn ridge migration' },
      { month: 10, status: 1, keyActivity: 'Patrolling foothill ridge lines' },
      { month: 11, status: 1, keyActivity: 'Wintering birds arrive from the far north' },
      { month: 12, status: 2, keyActivity: 'PEAK: Congregating near winter ungulate herds' },
    ],
    hotspots: [
      {
        name: 'Black Canyon of the Gunnison Rim Overlooks',
        region: 'co_gunnison_crested_butte',
        state: 'CO',
        elevation: '7,800 - 8,200 ft',
        publicLandType: 'National Park',
        accessNotes: 'Sheer 2,000-ft vertical granite canyon walls provide premier nesting ledges and soaring thermals.',
        bestTime: 'Late morning (10:00 AM - 1:00 PM) as canyon thermals develop',
        lat: 38.5750,
        lng: -107.7400,
      },
      {
        name: 'Red Rocks & Dinosaur Ridge (Front Range)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '6,200 ft',
        publicLandType: 'State Park',
        accessNotes: 'Famous migratory raptor ridge with panoramic views over Denver and the foothills.',
        bestTime: 'Midday sunny hours',
        lat: 39.6650,
        lng: -105.2050,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['500mm or 600mm f/4 prime', 'High continuous burst rate (20-30 fps)'],
      bestLighting: 'Morning or late afternoon sunlight hitting the bird from below as it banks along canyon walls.',
      fieldBehaviorNotes: 'Watch canyon rims when updrafts pick up around 10:30 AM. Eagles will use these invisible elevators to circle directly over your vantage point.',
      ethicalGuidelines: 'Federal Bald and Golden Eagle Protection Act: It is illegal to disturb nesting cliffs or collect feathers.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'Feather',
    colorAccent: 'sky',
  },
  {
    id: 'peregrine-falcon',
    name: 'American Peregrine Falcon',
    scientificName: 'Falco peregrinus anatum',
    category: 'bird',
    tagline: 'Fastest animal on planet earth: 200+ mph aerial stoops off towering canyon monoliths.',
    description: 'Reaching hunting dive speeds exceeding 240 miles per hour, the Peregrine Falcon is nature’s ultimate aerodynamic masterpiece. Nesting on sheer canyon cliffs and granite monoliths, they launch breath-taking high-altitude "stoops" to strike swifts, swallows, and waterfowl in midair.',
    imageUrl: 'https://images.unsplash.com/photo-1544943910-4c1dc44a0550?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Bold black helmet and dark malar sideburn stripes framing a white cheek',
      'Slate blue-gray back with finely barred black-and-white chest and belly',
      'Long, pointed falcon wings and streamlined torpedo-like flight silhouette'
    ],
    distinguishingTips: 'Pointed swept-back wings (unlike rounded hawk wings) and the prominent dark helmet and sideburns distinguish it from prairie falcons and merlins.',
    states: ['CO', 'UT'],
    elevationBands: ['foothills', 'montane'],
    regions: ['co_rmnp_frontrange', 'co_gunnison_crested_butte', 'sw_zion_canyon'],
    peakMonths: [5, 6, 7],
    keyEvents: ['Spring Courtship Flights (Apr)', 'Eyrie Prey Deliveries (May-Jun)', 'Fledgling Aerial Dogfights (Jul)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Wintering in coastal areas and southern river valleys' },
      { month: 2, status: 0, keyActivity: 'Wintering' },
      { month: 3, status: 1, keyActivity: 'Adults return to traditional cliff eyries' },
      { month: 4, status: 1, keyActivity: 'Aerial courtship; spectacular dives and food passes in mid-air' },
      { month: 5, status: 2, keyActivity: 'PEAK: High hunting activity delivering caught swifts and pigeons to cliff nest' },
      { month: 6, status: 2, keyActivity: 'PEAK: Downy chicks visible on cliff ledges exercising wings' },
      { month: 7, status: 2, keyActivity: 'PEAK: Fledged young performing thrilling mock aerial battles over canyon rims' },
      { month: 8, status: 1, keyActivity: 'Juveniles hone independent hunting skills' },
      { month: 9, status: 1, keyActivity: 'Autumn migration along mountain ridges' },
      { month: 10, status: 0, keyActivity: 'Most birds departed for winter grounds' },
      { month: 11, status: 0, keyActivity: 'Wintering' },
      { month: 12, status: 0, keyActivity: 'Wintering' },
    ],
    hotspots: [
      {
        name: 'Eldorado Canyon State Park (Boulder)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '6,300 ft',
        publicLandType: 'State Park',
        accessNotes: 'Famous sheer red sandstone walls (The Bastille and Redgarden Wall) with annual seasonal climbing closures for nesting eyries.',
        bestTime: 'Morning light illuminating the canyon walls',
        lat: 39.9300,
        lng: -105.2800,
      },
      {
        name: 'Angels Landing & Canyon Overlooks (Zion NP)',
        region: 'sw_zion_canyon',
        state: 'UT',
        elevation: '5,785 ft',
        publicLandType: 'National Park',
        accessNotes: 'Sheer vertical Navajo sandstone cliffs where falcons hunt white-throated swifts.',
        bestTime: 'Early morning golden hour',
        lat: 37.2690,
        lng: -112.9470,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['500mm f/4 or 600mm f/4', 'Extreme shutter speed (1/3200s to 1/4000s)'],
      bestLighting: 'Bright morning light illuminating the dark helmet against open blue sky or red canyon stone.',
      fieldBehaviorNotes: 'Peregrines fly at blistering speeds. Pre-focus on favorite cliff perches or watch for the explosive high-speed stoop when flocks of swifts scatter.',
      ethicalGuidelines: 'Respect seasonal climbing and hiking closures on cliff walls around active nesting eyries.',
      difficultyRating: 'Moderate Hike',
    },
    iconName: 'Feather',
    colorAccent: 'sky',
  },
  {
    id: 'trumpeter-swan',
    name: 'Trumpeter Swan',
    scientificName: 'Cygnus buccinator',
    category: 'bird',
    tagline: 'North America’s heaviest native waterfowl: pristine snow-white plumage on steaming thermal rivers.',
    description: 'Weighing over 25 pounds with an eight-foot wingspan, the Trumpeter Swan is North America’s largest native waterfowl. In winter, hundreds gather on the ice-free geothermal rivers of Yellowstone and Grand Teton, their bugling brassy calls echoing against sub-zero steam plumes and snowbound spruce forests.',
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Massive, entirely snowy-white body with an exceptionally long straight neck',
      'All-black wedge-shaped bill that merges smoothly into the forehead without yellow lore spots',
      'Thin salmon-pink or reddish "lipstick" stripe along the mouthline of the lower bill'
    ],
    distinguishingTips: 'Larger than the Tundra Swan; the Trumpeter has an entirely black bill that forms a seamless straight line into the eyes, whereas Tundra Swans usually show a yellow spot near the eye.',
    states: ['WY'],
    elevationBands: ['montane'],
    regions: ['wy_yellowstone_lamar', 'wy_grand_teton'],
    peakMonths: [1, 2, 12],
    keyEvents: ['Winter Thermal River Roosting (Dec-Feb)', 'Courtship Head-bobbing Dances (Feb-Mar)', 'Cygnet Hatching in Reeds (Jun)'],
    phenology: [
      { month: 1, status: 2, keyActivity: 'PEAK: High density on ice-free geothermal rivers; dramatic steam and hoarfrost' },
      { month: 2, status: 2, keyActivity: 'PEAK: Elaborate courtship head-bobbing, wing-quivering, and trumpet duets' },
      { month: 3, status: 1, keyActivity: 'Pairs disperse to mountain marshes as lakes thaw' },
      { month: 4, status: 1, keyActivity: 'Building massive floating island nests of reeds and sedges' },
      { month: 5, status: 1, keyActivity: 'Incubation on secluded mountain wetlands' },
      { month: 6, status: 1, keyActivity: 'Fluffy gray cygnets hatch and follow parents into open water' },
      { month: 7, status: 1, keyActivity: 'Adults molt flight feathers; flightless while caring for cygnets' },
      { month: 8, status: 1, keyActivity: 'Cygnets growing rapidly; feeding on submerged pondweeds' },
      { month: 9, status: 1, keyActivity: 'Cygnets practice flight take-offs across long water stretches' },
      { month: 10, status: 1, keyActivity: 'Family groups gather on staging wetlands' },
      { month: 11, status: 1, keyActivity: 'Moving toward warm geothermal rivers as cold fronts arrive' },
      { month: 12, status: 2, keyActivity: 'PEAK: Pristine sub-zero river scenes with frosty spruce backdrops' },
    ],
    hotspots: [
      {
        name: 'Madison River Geothermal Corridor (Yellowstone)',
        region: 'wy_yellowstone_lamar',
        state: 'WY',
        elevation: '6,800 ft',
        publicLandType: 'National Park',
        accessNotes: 'Warm springs prevent ice; swans float among rising morning steam plumes.',
        bestTime: 'Morning sub-zero hours (7:30 AM - 10:00 AM)',
        lat: 44.6400,
        lng: -110.8600,
      },
      {
        name: 'Flat Creek & National Elk Refuge (Jackson)',
        region: 'wy_grand_teton',
        state: 'WY',
        elevation: '6,230 ft',
        publicLandType: 'Wildlife Refuge',
        accessNotes: 'Roadside viewing platforms along Highway 89 with views of swans feeding in clear spring waters.',
        bestTime: 'Morning sun illuminating snowy Teton peaks',
        lat: 43.5100,
        lng: -110.7400,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['100-400mm or 500mm telephoto', 'Circular polarizer to manage bright water reflections'],
      bestLighting: 'Early morning backlighting through rising steam creates ethereal glowing silhouettes.',
      fieldBehaviorNotes: 'Swans require a long running takeoff (100 feet or more) paddling furiously across the water surface before getting airborne. Keep your lens framed wide to capture the dramatic water spray.',
      ethicalGuidelines: 'Do not approach winter roosting rivers on foot; cold stress burns vital calories.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'Feather',
    colorAccent: 'sky',
  },
  {
    id: 'common-loon',
    name: 'Common Loon',
    scientificName: 'Gavia immer',
    category: 'bird',
    tagline: 'Voice of the northern wilderness: ruby-red eyes, checkered velvet plumage, and haunting yodel calls.',
    description: 'With their haunting, echoing tremolo and yodel calls, Common Loons are the true voice of remote northern lakes. In summer, adults display immaculate black-and-white checkered velvet plumage, a striking iridescent black-green neck necklace, and glowing ruby-red eyes, frequently carrying tiny fuzzy chicks on their backs.',
    imageUrl: 'https://images.unsplash.com/photo-1555169062-013468b47731?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Striking black-and-white checkered back pattern with striped white neck collar',
      'Glossy velvet black head with intense, luminous ruby-red eyes',
      'Heavy dagger-like black bill held horizontally'
    ],
    distinguishingTips: 'Much heavier dagger-like bill and checkered back pattern than grebes; red eye and distinct black-and-white striped necklace are unmistakable in breeding season.',
    states: ['WA', 'AK'],
    elevationBands: ['plains', 'montane'],
    regions: ['pnw_olympic_rainforest', 'ak_kenai_coastal'],
    peakMonths: [6, 7, 8],
    keyEvents: ['Summer Breeding on Pristine Lakes (Jun-Jul)', 'Chicks Riding on Parent Backs (Jul)', 'Territorial Yodels at Dusk (Jun-Aug)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Wintering along coastal marine bays in dull gray-and-white plumage' },
      { month: 2, status: 0, keyActivity: 'Coastal marine foraging' },
      { month: 3, status: 1, keyActivity: 'Molting into dazzling summer breeding plumage' },
      { month: 4, status: 1, keyActivity: 'Migrating inland to clear mountain lakes as ice melts' },
      { month: 5, status: 1, keyActivity: 'Establishing lake territories; building shore nests' },
      { month: 6, status: 2, keyActivity: 'PEAK: Haunting yodel calls echo across lakes; incubation on shoreline nests' },
      { month: 7, status: 2, keyActivity: 'PEAK: Tiny downy chicks hatch and ride on parents’ backs for warmth and safety' },
      { month: 8, status: 2, keyActivity: 'PEAK: Parents diving and feeding small fish to growing juveniles' },
      { month: 9, status: 1, keyActivity: 'Juveniles practicing diving and independent foraging' },
      { month: 10, status: 1, keyActivity: 'Departing inland lakes ahead of ice freeze' },
      { month: 11, status: 0, keyActivity: 'Coastal wintering' },
      { month: 12, status: 0, keyActivity: 'Coastal wintering' },
    ],
    hotspots: [
      {
        name: 'Lake Crescent & Lake Quinault (Olympic NP)',
        region: 'pnw_olympic_rainforest',
        state: 'WA',
        elevation: '580 ft',
        publicLandType: 'National Park',
        accessNotes: 'Glacier-carved crystal-clear deep lakes surrounded by temperate rainforest.',
        bestTime: 'Calm morning water (6:30 AM - 9:30 AM) with misty water reflections',
        lat: 48.0600,
        lng: -123.8000,
      },
      {
        name: 'Kenai National Wildlife Refuge Canoe Lakes',
        region: 'ak_kenai_coastal',
        state: 'AK',
        elevation: '300 ft',
        publicLandType: 'Wildlife Refuge',
        accessNotes: 'Secluded pristine boreal lakes accessible by canoe or shoreline trails.',
        bestTime: 'Evening golden hour and midnight sun twilight',
        lat: 60.5000,
        lng: -150.5000,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['400mm or 500mm telephoto', 'Low-profile kayak or canoe mount'],
      bestLighting: 'Early morning glassy water reflections; soft directional light reveals the ruby-red eye color.',
      fieldBehaviorNotes: 'Loons have heavy solid bones and can sink like a submarine to change water depth. When chicks are small, one parent will carry them on its back while the other dives for minnows.',
      ethicalGuidelines: 'Keep boats at least 150 feet away. If the loon raises its neck and gives a tremolo "laugh" call, you are too close and causing alarm.',
      difficultyRating: 'Easy / Roadside',
    },
    iconName: 'Feather',
    colorAccent: 'sky',
  },

  // ==========================================
  // WILDFLOWERS & BOTANICALS
  // ==========================================
  {
    id: 'calypso-orchid',
    name: 'Calypso Orchid (Fairy Slipper)',
    scientificName: 'Calypso bulbosa',
    category: 'wildflower',
    tagline: 'Elusive gem of the montane forest floor: delicate magenta slipper lip and yellow beard.',
    description: 'Regarded as one of North America’s most exquisite native orchids, the Calypso Orchid or Fairy Slipper blooms for just two to three weeks right after snowmelt on deep, mossy, shaded forest floors. Each plant produces a single jewel-like magenta-pink flower with an inflated shoe-like pouch and a delicate yellow beard.',
    imageUrl: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Single solitary magenta-pink flower nodding atop a delicate 3-to-6 inch purplish stem',
      'Prominent inflated lower lip resembling a miniature lady’s slipper with purple streaks and yellow beard',
      'Single solitary dark green oval leaf at the base that overwinters under snow'
    ],
    distinguishingTips: 'Unlike Lady’s Slipper orchids (Cypripedium) which have multiple leaves and large blooms, Calypso has only one solitary basal leaf and a delicate single jewel bloom.',
    states: ['CO', 'WA'],
    elevationBands: ['montane'],
    regions: ['co_rmnp_frontrange', 'co_san_juan', 'pnw_cascades_rainier'],
    peakMonths: [5, 6],
    keyEvents: ['Post-Snowmelt Moss Bloom (May-Jun)', 'Solitary Leaf Overwintering (Autumn)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Dormant solitary leaf beneath heavy snowpack' },
      { month: 2, status: 0, keyActivity: 'Snowbound' },
      { month: 3, status: 0, keyActivity: 'Snowbound' },
      { month: 4, status: 0, keyActivity: 'Early snow clearing in lower montane spruce corridors' },
      { month: 5, status: 2, keyActivity: 'PEAK: Solitary purple flower bud rises directly from mossy duff' },
      { month: 6, status: 2, keyActivity: 'PEAK: Peak bloom in cool, moist, shaded Douglas fir and lodgepole forest glades' },
      { month: 7, status: 0, keyActivity: 'Bloom fades; single seed capsule develops as old leaf withers' },
      { month: 8, status: 0, keyActivity: 'Seed dispersal by wind' },
      { month: 9, status: 1, keyActivity: 'New solitary winter leaf emerges to photosynthesize under low autumn light' },
      { month: 10, status: 0, keyActivity: 'Covered by first persistent snow' },
      { month: 11, status: 0, keyActivity: 'Snowbound' },
      { month: 12, status: 0, keyActivity: 'Snowbound' },
    ],
    hotspots: [
      {
        name: 'Wild Basin & Ouzel Falls Forest Trail (RMNP)',
        region: 'co_rmnp_frontrange',
        state: 'CO',
        elevation: '8,500 - 9,200 ft',
        publicLandType: 'National Park',
        accessNotes: 'Mossy, shaded forest floor beneath ancient Douglas fir and Engelmann spruce.',
        bestTime: 'Morning filtered dappled sunlight',
        lat: 40.2100,
        lng: -105.5800,
      },
      {
        name: 'Telluride Valley Floor & Bear Creek Preserve (San Juans)',
        region: 'co_san_juan',
        state: 'CO',
        elevation: '8,750 ft',
        publicLandType: 'State Park',
        accessNotes: 'Cool north-facing shaded slopes along forested canyon creek trails.',
        bestTime: 'Mid-morning soft forest light',
        lat: 37.9350,
        lng: -107.8100,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['90mm or 105mm f/2.8 Macro lens', 'Small mini-tripod or bean bag for ground placement'],
      bestLighting: 'Soft diffused shade. Use a small white reflector or LED fill light at low power to illuminate the inside of the slipper pouch.',
      fieldBehaviorNotes: 'The plant stands only 3 to 6 inches tall. Lie flat on the ground and shoot straight-on at eye-level to isolate the jewel-like structure against dark green moss bokeh.',
      ethicalGuidelines: 'Calypso orchids have extremely delicate fungal root associations. NEVER step on the moss nearby or pick the flower; picking destroys the bulb and kills the plant.',
      difficultyRating: 'Moderate Hike',
    },
    iconName: 'Flower2',
    colorAccent: 'emerald',
  },
  {
    id: 'avalanche-glacier-lily',
    name: 'Glacier & Avalanche Lily',
    scientificName: 'Erythronium grandiflorum / montanum',
    category: 'wildflower',
    tagline: 'Snow-melting pioneers: brilliant yellow and pure white reflexed petals pushing through alpine snowpacks.',
    description: 'Known as the ultimate snow-melting pioneers, Glacier Lilies (vivid bright yellow) and Avalanche Lilies (radiant pure white) push their flower buds right through the edges of melting alpine snowdrifts. In June and July, entire subalpine meadows become carpeted in tens of thousands of delicate nodding blooms beneath glacier-clad volcano peaks.',
    imageUrl: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?auto=format&fit=crop&w=800&q=80',
    identificationMarks: [
      'Gracefully recurved / reflexed petals swept upward like shooting stars',
      'Long prominent protruding stamens with bright red, yellow, or white anthers',
      'Smooth, glossy, paired oblong green leaves emerging at the snow edge'
    ],
    distinguishingTips: 'Distinguished by strongly reflexed upward-pointing petals and solitary nodding flower structure growing directly alongside melting snowdrifts.',
    states: ['CO', 'WA'],
    elevationBands: ['montane', 'subalpine'],
    regions: ['co_gunnison_crested_butte', 'pnw_cascades_rainier'],
    peakMonths: [6, 7],
    keyEvents: ['Snowdrift Edge Emergence (Jun)', 'Subalpine Basin Superbloom (Jul)', 'Seed Pod Maturation (Aug)'],
    phenology: [
      { month: 1, status: 0, keyActivity: 'Deep bulb dormancy under heavy winter snowpack' },
      { month: 2, status: 0, keyActivity: 'Dormant' },
      { month: 3, status: 0, keyActivity: 'Dormant' },
      { month: 4, status: 0, keyActivity: 'Dormant under high-elevation snow' },
      { month: 5, status: 1, keyActivity: 'Lower montane snowmelt triggers early shoot growth' },
      { month: 6, status: 2, keyActivity: 'PEAK: Millions of bright yellow Glacier Lilies emerge right along retreating snowbanks' },
      { month: 7, status: 2, keyActivity: 'PEAK: Pure white Avalanche Lilies carpet subalpine slopes beneath Mount Rainier' },
      { month: 8, status: 1, keyActivity: 'Blooms fade; attractive three-chambered upright seed capsules form' },
      { month: 9, status: 0, keyActivity: 'Foliage withers into autumn dormancy' },
      { month: 10, status: 0, keyActivity: 'Early winter snow buries high meadows' },
      { month: 11, status: 0, keyActivity: 'Dormant under snow' },
      { month: 12, status: 0, keyActivity: 'Dormant under snow' },
    ],
    hotspots: [
      {
        name: 'Paradise & Mazama Ridge (Mount Rainier)',
        region: 'pnw_cascades_rainier',
        state: 'WA',
        elevation: '5,400 ft',
        publicLandType: 'National Park',
        accessNotes: 'Legendary avalanche lily superblooms blanketing ridgelines with Mount Rainier towering behind.',
        bestTime: 'Morning sun and sunset alpenglow',
        lat: 46.7800,
        lng: -121.7300,
      },
      {
        name: 'Snodgrass Trail & Washington Gulch (Crested Butte)',
        region: 'co_gunnison_crested_butte',
        state: 'CO',
        elevation: '9,600 - 10,200 ft',
        publicLandType: 'National Forest',
        accessNotes: 'Vast carpets of bright yellow Glacier Lilies pushing through aspen groves in early summer.',
        bestTime: 'Morning light before midday wind',
        lat: 38.9200,
        lng: -106.9800,
      },
    ],
    photographyGuide: {
      recommendedLenses: ['16-35mm wide angle for flower-and-mountain compositions', '100mm Macro'],
      bestLighting: 'Backlight through the translucent petals makes the flowers glow like golden or crystal lanterns.',
      fieldBehaviorNotes: 'Get your camera low to the ground pointing up through the nodding flowers toward mountain peaks in the background.',
      ethicalGuidelines: 'Subalpine meadow soils are extremely fragile when wet from snowmelt. Stay strictly on designated boardwalks and gravel trails.',
      difficultyRating: 'Moderate Hike',
    },
    iconName: 'Flower2',
    colorAccent: 'emerald',
  },
];
'''

with open('src/data/additional-species.ts', 'w', encoding='utf-8') as f:
    f.write(ADDITIONAL_SPECIES_CODE)

print("Successfully written additional-species.ts with 40 fully enriched subjects!")
